---
stages:
  - image

###
# Template
###

.docker:
  image: docker:20.10
  services:
    - docker:dind
  variables:
    DOCKER_HOST: 'tcp://docker:2376'
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
    DOCKER_TLS_CERTDIR: '/certs'
    DOCKER_TLS_VERIFY: 1
    DOCKER_BUILDKIT: 1
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

###
# Images
###

image:buildx:
  stage: image
  extends: .docker
  only:
    - tags
  script:
    - |
      docker build \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        --cache-from ${CI_REGISTRY_IMAGE}/buildx:latest \
        -t ${CI_REGISTRY_IMAGE}/buildx:${CI_COMMIT_REF_SLUG} \
        -t ${CI_REGISTRY_IMAGE}/buildx:latest \
        ./buildx/
  after_script:
    - docker push ${$CI_REGISTRY_IMAGE}/buildx:${CI_COMMIT_REF_SLUG}
    - docker push ${CI_REGISTRY_IMAGE}/buildx:latest
